/*
 * Defines for substrings used in http messages
 *
 * TODO: add explanation
 */
enum twitter_statuses_home_timeline_start{
    HOME_START_HEAD,
    HOME_START_COUNT,
    HOME_START_COUNT_VAL,
    HOME_START_SINCE_ID,
    HOME_START_SINCE_ID_VAL,
    HOME_START_MAX_ID,
    HOME_START_MAX_ID_VAL,
    HOME_START_TRIM_USER,
    HOME_START_TRIM_USER_VAL,
    HOME_START_EXCLUDE_REPLIES,
    HOME_START_EXCLUDE_REPLIES_VAL,
    HOME_START_CONTRIBUTOR_DETAILS,
    HOME_START_CONTRIBUTOR_DETAILS_VAL,
    HOME_START_INCLUDE_ENTITIES,
    HOME_START_INCLUDE_ENTITIES_VAL,
    HOME_START_N
};

enum oauth_home_timeline_base_str{
    HOME_BASE_HEAD,
    HOME_BASE_COUNT,
    HOME_BASE_COUNT_VAL,
    HOME_BASE_CONTRIBUTOR_DETAILS,
    HOME_BASE_CONTRIBUTOR_DETAILS_VAL,
    HOME_BASE_EXCLUDE_REPLIES,
    HOME_BASE_EXCLUDE_REPLIES_VAL,
    HOME_BASE_INCLUDE_ENTITIES,
    HOME_BASE_INCLUDE_ENTITIES_VAL,
    HOME_BASE_MAX_ID,
    HOME_BASE_MAX_ID_VAL,
    HOME_BASE_OAUTH_CONSUMER_KEY,
    HOME_BASE_OAUTH_CONSUMER_KEY_VAL,
    HOME_BASE_OAUTH_NONCE,
    HOME_BASE_OAUTH_NONCE_VAL,
    HOME_BASE_OAUTH_SIGNATURE_METHOD,
    HOME_BASE_OAUTH_TIMESTAMP,
    HOME_BASE_OAUTH_TIMESTAMP_VAL,
    HOME_BASE_OAUTH_TOKEN,
    HOME_BASE_OAUTH_TOKEN_VAL,
    HOME_BASE_OAUTH_VERSION,
    HOME_BASE_SINCE_ID,
    HOME_BASE_SINCE_ID_VAL,
    HOME_BASE_TRIM_USER,
    HOME_BASE_TRIM_USER_VAL,
    HOME_BASE_N
};

enum oauth_home_timeline_auth_header{
    HOME_AUTH_OAUTH_NONCE,
    HOME_AUTH_OAUTH_NONCE_VAL,
    HOME_AUTH_OAUTH_SIGNATURE,
    HOME_AUTH_OAUTH_SIGNATURE_VAL,
    HOME_AUTH_OAUTH_SIGNATURE_METHOD,
    HOME_AUTH_OAUTH_TIMESTAMP,
    HOME_AUTH_OAUTH_TIMESTAMP_VAL,
    HOME_AUTH_OAUTH_TOKEN,
    HOME_AUTH_OAUTH_TOKEN_VAL,
    HOME_AUTH_OAUTH_VERSION,
    HOME_AUTH_N
};

enum substr_ids{
    HOME_START,
    HOME_BASE,
    HOME_AUTH
};

#define SUBSTR_IDS {HOME_START_N, HOME_BASE_N, HOME_AUTH_N}

